# general
batch_size: 128
input_size: 112
embd_shape: 512
sub_name: 'arc_res50_kface_finetune'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead # 'ArcHead', 'NormHead'
is_ccrop: False # central-cropping or not

# train
train_dataset: './data/kface_bin.tfrecord'
binary_img: True
num_classes: 390
num_samples: 9360
epochs: 50
base_lr: 0.001
w_decay: !!float 5e-4
save_steps: 730 # 9360 // 128 * 10

# test
test_dataset: '/your/path/to/test_dataset'
